name: Build and Deploy WebApp

env:
  DOTNET_VERSION: '6'
  AZURE_WEBAPP_NAME: 'inte-poc'
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test BPCalculator.sln --filter FullyQualifiedName~UnitTests --logger trx --results-directory "TestResults"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
            name: dotnet-results
            path: TestResults
          # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: ./
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy_integration:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Integration
    env:
      K6_BROWSER_ENABLED: true  

    steps:
      - name: Download artifact for deployment
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          slot-name: 'testing'
          

      - name: Download K6 test file
        run: |
          mkdir k6_scripts
          wget -O k6_scripts/performance.js https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/.github/k6/performance.js

      - name: Pull Docker image for k6
        run: docker pull grafana/k6

      - name: Run k6 load test, capture report
        run: docker run -i grafana/k6 run - <k6_scripts/performance.js > k6report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: k6report
          path: k6report.txt

  execute_end_to_end:
    runs-on: ubuntu-latest
    needs: deploy_integration
    environment:
      name: Integration
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy
    steps:
          - uses: actions/checkout@v3
          
          - name: Set up .NET Core
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: ${{ env.DOTNET_VERSION }}

          - name: Build EndToEndTests project
            run: dotnet build EndToEndTests/EndToEndTests.csproj --configuration Release

          - name: Update Playwright Settings File
            env:
              AZURE_APP_SERVICE_URL: ${{ secrets.AZURE_APP_SERVICE_URL }}
            run: |
              echo "BaseUrl before sed: $(grep 'BaseUrl' EndToEndTests/playwrightSettings.json)"
              echo "AZURE_APP_SERVICE_URL: $AZURE_APP_SERVICE_URL"
              sed -i 's|"BaseUrl": "http://localhost:5000/"|"BaseUrl": "'"$AZURE_APP_SERVICE_URL"'"|g' EndToEndTests/playwrightSettings.json
              echo "BaseUrl after sed: $(grep 'BaseUrl' EndToEndTests/playwrightSettings.json)"

          - name: Run Playwright E2E Tests
            run: |
              dotnet test EndToEndTests/EndToEndTests.csproj
            env:
                HOME: /root